### ISSUE TITLE
(*Config).homeDirectory redeclared in this block

### ISSUE THREAD

**Issue by realdoug** [heroku/force#150]
I get the following error when i run "go get github.com/heroku/force"

$ go get github.com/heroku/force
\# github.com/ddollar/config
go/src/github.com/ddollar/config/windows.go:8: (*Config).homeDirectory redeclared in this block
	previous declaration at go/src/github.com/ddollar/config/posix.go:9

I'm on Ubuntu.  Is this due to a setting on my system, or just a bug in the code?

**Comment by dcarroll** [comment]
This is due to the way you have go setup on your machine.  The go/src
directory is where you should pull in the force toolkit.  There is also a
-n flag on go get that has helped solve this problem as well.

On Tue, Mar 17, 2015 at 10:01 AM, Doug Friedman <notifications@github.com>
wrote:

> I get the following error when i run "go get github.com/heroku/force"
>
> $ go get github.com/heroku/force
> github.com/ddollar/config
>
> go/src/github.com/ddollar/config/windows.go:8: (*Config).homeDirectory
> redeclared in this block
> previous declaration at go/src/github.com/ddollar/config/posix.go:9
>
> I'm on Ubuntu. Is this due to a setting on my system, or just a bug in the
> code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/150>.
>



-- 
Thanks,
Dave

**Comment by realdoug** [comment]
Earlier I had just deleted windows.go from the ddollar/config package which was super hacky but worked.  I uninstalled, reproduced the issue and then tried with -n and that works for me.

Would love to figure out what it is about my go setup would cause this.  "go get" definitely puts the force toolkit in my go/src directory.

**Comment by jbizzle** [comment]
I think the problem is that there is a bug in `ddollar/config`, in that the `windows.go` file should either be named something like `config_windows.go` or should have the build header at the top (`// +build windows`).

It's complicated though, because not only does `ddollar/config` need to change but also `heroku/force` needs to update its go deps accordingly.

Would be nice to get back to a standard vanilla invocation of `go get ...` without the `-n`.

@dcarroll -- It looks like you've [https://github.com/devangel/config](done this already), but it's not part of `heroku/force`. Any reason not to use your version, which will work as expected?

**Comment by ViViDboarder** [comment]
FYI this is still broken. I can create an issue on the actual ddollar/config repo if you'd prefer, but it's still broken.

**Comment by cwarden** [comment]
Prior to go 1.4, the filename, `windows.go`, was [treated as an implicit build constraint](https://golang.org/doc/go1.4#filenames).

**Comment by dcarroll** [comment]
Oh, this is interesting. I'll read further.

On Wed, Dec 9, 2015 at 2:40 PM, Christian G. Warden <
notifications@github.com> wrote:

> Prior to go 1.4, the filename, windows.go, was treated as an implicit
> build constraint <https://golang.org/doc/go1.4#filenames>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/150#issuecomment-163424177>.
>



-- 
Thanks,
Dave

**Comment by rtconner** [comment]
I'm getting this issue also. I don't know anything about go to help debug.

**Comment by flyingoctopus** [comment]
bump. Issue is still persisting

**Comment by cwarden** [comment]
This will be fixed when #221 is merged.  See 3c4f902329cce4d7bdd6a28f3384926251914cae.
