### ISSUE TITLE
force login -u -p fails when using special characters on OSX

### ISSUE THREAD

**Issue by john-benson** [heroku/force#273]
Interesting issue I found when using special characters to login using the command line on OSX:

force login -u=my.fancy.user@mycompany.com -p=h0vo!2}BaO8Qk2lt/>\5X;HaQ

Produces:
-bash: !2: event not found

Updating my password to use only letters and numbers resolves the issue.

When I get some time, I'll run the test against Windows and see if a similar issue crops up. When I get some MORE time I'll take a look and try to offer a PR ;)

**Comment by brianmfear** [comment]
That's not a force.com CLI issue, but a "shell" issue. Certain characters in the shell have special meaning, and you have to "escape" them in order to avoid them being interpreted incorrectly. There's nothing the Force.com CLI can do to prevent these types of problems. You can try surrounding your parameter in single quotes, as noted on this [stack overflow question](http://superuser.com/questions/133780/in-bash-how-do-i-escape-an-exclamation-mark).

**Comment by john-benson** [comment]
Ahh makes sense! I'm not a big Mac user so it caught me off guard.

Thanks for the Stack Overflow link!

Love the project! Makes integration with SF a breeze.
