### ISSUE TITLE
Release link broken?

### ISSUE THREAD

**Issue by jziesing** [heroku/force#310]
I think the release link for Darwin/mac is broken.  I downloaded it from https://force-cli.heroku.com/ and from the releases page on github but they both are unmarked files containing bits or something.  

The https://force-cli.heroku.com/ makes it seem like you are getting a .dmg and I am not sure if that is what I should expect or if this bits file is actually the correct file.

Please let me know if the release link is working

Thanks,

Jack

EDIT:

 Dave I just read your previous post on the future of this project.  All sounds good and very cool actually.   I am still curious if an older release will be available?

**Comment by dcarroll** [comment]
It is a file with no extension, you may need to run chmod +x force.

Sent from my iPhone

On Aug 28, 2016, at 11:44 AM, Jack Ziesing <notifications@github.com> wrote:

I think the release link for Darwin/mac is broken. I downloaded it from
https://force-cli.heroku.com/ and from the releases page on github but they
both are unmarked files containing bits or something.

The https://force-cli.heroku.com/ makes it seem like you are getting a .dmg
and I am not sure if that is what I should expect or if this bits file is
actually the correct file.

Please let me know if the release link is working

Thanks,

Jack

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/heroku/force/issues/310>, or mute the thread

**Comment by jziesing** [comment]
oh I got it, thank you!
