### ISSUE TITLE
Error when trying to push a Flow

### ISSUE THREAD

**Issue by ericrsmith35** [heroku/force#362]
I get an error when trying this command:
force push -t Flow -n Create_Child_Account_from_Account-6.flow

Validating and deploying push...
ERROR: exec: "ls": executable file not found in %!P(MISSING)ATH%!
(MISSING)

**Comment by dcarroll** [comment]
Not sure flow is supported, try without file extension.

Sent from my iPhone

On Dec 22, 2016, at 3:13 PM, Eric Smith <notifications@github.com> wrote:

I get an error when trying this command:
force push -t Flow -n Create_Child_Account_from_Account-6.flow

Validating and deploying push...
ERROR: exec: "ls": executable file not found in %!P(MISSING)ATH%!
(MISSING)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/heroku/force/issues/362>, or mute the thread

**Comment by ericrsmith35** [comment]
I get the same error without the extension.

**Comment by dcarroll** [comment]
Ok, I think I've found the issue. I think you are on windows and instead of "dir" and "ls" command is being used to search for wildcard values somewhere in the process.  This is a no-no as obviously it is not cross platform.  I will fix the bug.

**Comment by dcarroll** [comment]
Flow pushes are working for me and I have fixed the issue with the "ls" error

**Comment by ericrsmith35** [comment]
Thank You.
